osx_image: xcode8.3
sudo: required
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm test --silent
- npm run make -- --target=$TRAVIS_OS_NAME
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VIa1ItTZ30NPiT2DGMEOAmfu5Go+ApHLQxcvq/X/FBQ4kvDNrrEpNfNTm77VwBpLXgFKz5ldvjVwx4J22gjJIYRTDlt3Rhx22Ob82H67wq9rzsPDc4TOYrYSVTQW8EYN8ktDjVR5PiQWcYKMx1JKj5V7xWrrFcQTJKxvYqTGSvzG3EKHU6UR+dSlXLSvf0Bt+9+ZUc6QhtF40Jr4SY6Fjs6ZTW9oII3ZzrEjZ9oxXpUdhnUCWOQlEwNu5lNStMac+kAQT1jNfb/l41oRVTk/qAzCjia6LK/x0UxGnhNCFSPFI8C0YQk3sMxwE9k65rUxKrZYdWYo+Zb4CR1UpM0wJ2T/sAfys7eAqk+W76GEb39zp/6TnXff2JprDCrKdz6X+q8K6YdWDuNNPNjbnvv8ajyW5gmcscJTikXhEiG8gPO/7cJ4j1sg+wKLb9XwAI2RLnOeRfyblpTblNsAtivx8MrK+a1hKkCOY5UQ2o3SjEXn75Xm5U02B+NN0pXWQUvi+JDXJ7xVJTlfhzdPkID297HHhVuzEKQDM3YGlW9DFUOK5yrWblGXhg+bNEcDHWwze5onpAxm4Sv0u0dVaFOU4T8Mk4SjSlXQMhv3+RzTdBwZ0/0qrVQpgNFjPD0CxmoL8cvZs56772nZKi7vwhNozkvsklot1gWvLd+vbd4fJ4E=
  file_glob: true
  file: out/make/*
  on:
    repo: dkundel/tunes
    tags: true